apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:0472367e0a9e19b03341d3c57dc700cfa2384c329d1754fcfab69a23609afeb7
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:b2b073a82ecc46d7dfeec61672d2a45e5b28e8cdfb1d77a666e3f90e77c2fe4f
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
