apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:baf89af4af7e2dbd886bbf647d2ea66a210f08349494c9d3d4243f453bfbe64c
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:b2b073a82ecc46d7dfeec61672d2a45e5b28e8cdfb1d77a666e3f90e77c2fe4f
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
