apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:53a9aded63ab97712d381e229d1f868a14e12de5e5d45cd28cc6cd7185f40f72
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:b2b073a82ecc46d7dfeec61672d2a45e5b28e8cdfb1d77a666e3f90e77c2fe4f
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
