apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9e0f48b6f6ac259a65be1767f09aa75232c497934999d77894ac297cb8f1f7b4
  name: image-registry.openshift-image-registry.svc:5000/default/app-git
  newName: image-registry.openshift-image-registry.svc:5000/default/app-git
- digest: sha256:0175e4f6c62642caac62c2dbeb37182c2972c2003101dd8bcee5d2bef2f733b1
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:b2b073a82ecc46d7dfeec61672d2a45e5b28e8cdfb1d77a666e3f90e77c2fe4f
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
