apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:67934be65669eefa27b38f15f86349341038dd0a05e33ee57c4464a51b0e8bb0
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:317058417fe29c0d2a9aed380930cb08f0df4581111ae5d221e58e17f81cc929
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
