apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:b11196747ebcd71e8eae4ff556551f26af8938728c0909ec96791251487b27b4
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
- digest: sha256:eb81919149bf898b651e049cb4e377c70b6a4a41a790b1f31dfbb4269302b90d
  name: quay.io/waeshalaby/vote-ui
  newName: quay.io/waeshalaby/vote-ui
