apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:03fe0f86377502ef2e6793faebd85acbf054aa5284990ce12b5c4b05e497519a
  name: quay.io/waeshalaby/vote-api
  newName: quay.io/waeshalaby/vote-api
